name: main

on:
    push:
        branches:
            - "main"
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        if: startsWith(github.event.ref, 'refs/tags/v')
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.18
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build frontend
              run: cd web && npm i --also=dev && sed -i 's/dev = true/dev = false/g' src/Api.js && npm run build && mv dist/* ../static
            - name: login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  version: latest
                  args: release --rm-dist --skip-validate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
